version: '3.8'

services:
  fastapi:
    build:
      context: ./mini_groq_project  # Path to your FastAPI project
      dockerfile: dockerfile
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}  # Pass the API key
    expose:
      - "5000"  # Expose the FastAPI port internally

  nginx:
    build:
      context: ./nginx  # Path to your Nginx project
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
