name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify your Python version

      - name: Install dependencies
        run: |
          cd mini_groq_project
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          cd mini_groq_project
          pytest
